import React, { useState } from 'react';
import {
  Search,
  FileText,
  ShieldCheck,
  ShieldX,
  Pause,
  Receipt,
  Package,
  Truck,
  MapPin,
  CheckCircle2,
  Clock,
  XCircle,
  PackageX,
  RefreshCw,
  User,
  Building2,
  Calendar,
  ArrowRight,
  Boxes,
  BadgeIndianRupee,
  ScanSearch
} from 'lucide-react';
import { Order, OrderStatus } from '../../types';
import { useAuth } from '../../context/AuthContext';
import { isCompanyAllowedForUser } from '../../lib/supabase';

interface OrderTrackerViewProps {
  orders: Order[];
}

interface TrackStage {
  id: string;
  label: string;
  sublabel: string;
  icon: any;
  color: string;
  glow: string;
  matchStatuses: OrderStatus[];
  terminalBad?: boolean; // RED terminal (cancelled / rejected)
}

const STAGES: TrackStage[] = [
  {
    id: 'placed',
    label: 'Order Placed',
    sublabel: 'Salesperson submitted the order',
    icon: FileText,
    color: '#94a3b8',
    glow: 'rgba(148,163,184,0.3)',
    matchStatuses: ['DRAFT', 'SUBMITTED']
  },
  {
    id: 'admin_review',
    label: 'System Admin Review',
    sublabel: 'Account check & approval',
    icon: ShieldCheck,
    color: '#fbbf24',
    glow: 'rgba(251,191,36,0.3)',
    matchStatuses: ['APPROVED', 'HELD']
  },
  {
    id: 'billing',
    label: 'Billing & Invoice',
    sublabel: 'Invoice generated by accounts',
    icon: Receipt,
    color: '#a78bfa',
    glow: 'rgba(167,139,250,0.3)',
    matchStatuses: ['BILLED']
  },
  {
    id: 'dispatch_ready',
    label: 'Dispatch Ready',
    sublabel: 'Stock picked & packed at warehouse',
    icon: Package,
    color: '#38bdf8',
    glow: 'rgba(56,189,248,0.3)',
    matchStatuses: ['DISPATCH_PENDING', 'READY_FOR_PICKUP', 'PARTIALLY_DISPATCHED']
  },
  {
    id: 'dispatched',
    label: 'Dispatched / In Transit',
    sublabel: 'Order shipped to party location',
    icon: Truck,
    color: '#f97316',
    glow: 'rgba(249,115,22,0.3)',
    matchStatuses: ['DISPATCHED', 'OUT_FOR_DELIVERY']
  },
  {
    id: 'delivered',
    label: 'Delivered & Closed',
    sublabel: 'Order received by party. Settled.',
    icon: CheckCircle2,
    color: '#34d399',
    glow: 'rgba(52,211,153,0.35)',
    matchStatuses: ['DELIVERED', 'COMPLETED']
  }
];

const BAD_STATUSES: OrderStatus[] = ['CANCELLED', 'REJECTED'];

function getActiveStageIndex(status: OrderStatus): number {
  if (BAD_STATUSES.includes(status)) return -1;
  for (let i = STAGES.length - 1; i >= 0; i--) {
    if (STAGES[i].matchStatuses.includes(status)) return i;
  }
  return 0;
}

function getStatusLabel(status: OrderStatus): string {
  const map: Record<string, string> = {
    DRAFT: 'Draft',
    SUBMITTED: 'Submitted — Awaiting Admin Approval',
    APPROVED: 'Approved by System Admin',
    HELD: 'On Hold — Admin Review Pending',
    REJECTED: 'Rejected by Admin',
    BILLED: 'Invoice Generated',
    DISPATCH_PENDING: 'Dispatch Pending',
    READY_FOR_PICKUP: 'Ready for Pickup at Warehouse',
    PARTIALLY_DISPATCHED: 'Partially Dispatched',
    DISPATCHED: 'Dispatched — In Transit',
    OUT_FOR_DELIVERY: 'Out for Delivery',
    DELIVERED: 'Delivered to Party',
    COMPLETED: 'Completed & Settled',
    CANCELLED: 'Cancelled'
  };
  return map[status] || status;
}

export const OrderTrackerView: React.FC<OrderTrackerViewProps> = ({ orders }) => {
  const { currentUser } = useAuth();
  const [query, setQuery] = useState('');
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [showDropdown, setShowDropdown] = useState(false);

  const accessibleOrders = orders.filter(o =>
    isCompanyAllowedForUser(o.company_name, currentUser?.company_handle)
  );

  const suggestions = query.length >= 2
    ? accessibleOrders.filter(o =>
        o.order_number.toLowerCase().includes(query.toLowerCase()) ||
        (o.agency_name || '').toLowerCase().includes(query.toLowerCase())
      ).slice(0, 8)
    : [];

  const handleSelect = (order: Order) => {
    setSelectedOrder(order);
    setQuery(order.order_number);
    setShowDropdown(false);
  };

  const isCancelled = selectedOrder && BAD_STATUSES.includes(selectedOrder.status);
  const isHeld = selectedOrder?.status === 'HELD';
  const activeIdx = selectedOrder ? getActiveStageIndex(selectedOrder.status) : -1;

  return (
    <div className="page-body">

      {/* Header */}
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 800 }}>Order Tracker</h1>
        <p style={{ fontSize: '0.85rem', color: '#94a3b8', marginTop: 4 }}>
          Search any order number or party name to see its live status & journey
        </p>
      </div>

      {/* Search Box */}
      <div style={{ maxWidth: 600, position: 'relative', marginBottom: '2.5rem' }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: '0.75rem',
          background: '#141f36', border: '2px solid #1e3a5f',
          borderRadius: 14, padding: '0.75rem 1.1rem',
          boxShadow: '0 0 0 0 rgba(56,189,248,0)',
          transition: 'box-shadow 0.2s'
        }}
          onFocus={() => setShowDropdown(true)}
        >
          <Search size={20} color="#38bdf8" />
          <input
            type="text"
            placeholder="Enter order number (e.g. PRG-08082026-001) or party name..."
            value={query}
            onChange={e => { setQuery(e.target.value); setShowDropdown(true); setSelectedOrder(null); }}
            onFocus={() => setShowDropdown(true)}
            onBlur={() => setTimeout(() => setShowDropdown(false), 180)}
            style={{
              background: 'transparent', border: 'none', outline: 'none',
              color: '#f8fafc', fontSize: '0.9rem', width: '100%', fontWeight: 600
            }}
            autoComplete="off"
          />
          {query && (
            <button onClick={() => { setQuery(''); setSelectedOrder(null); }}
              style={{ background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', lineHeight: 1 }}>
              <XCircle size={16} />
            </button>
          )}
        </div>

        {/* Dropdown suggestions */}
        {showDropdown && suggestions.length > 0 && (
          <div style={{
            position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 999,
            background: '#1e293b', border: '1px solid #334155',
            borderRadius: 12, marginTop: 6, overflow: 'hidden',
            boxShadow: '0 12px 30px rgba(0,0,0,0.5)'
          }}>
            {suggestions.map(o => (
              <div key={o.id}
                onMouseDown={() => handleSelect(o)}
                style={{
                  padding: '0.75rem 1rem', cursor: 'pointer',
                  borderBottom: '1px solid #0f172a',
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center'
                }}
                onMouseEnter={e => (e.currentTarget.style.background = '#0f172a')}
                onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
              >
                <div>
                  <div style={{ fontWeight: 800, color: '#38bdf8', fontFamily: 'monospace', fontSize: '0.875rem' }}>
                    {o.order_number}
                  </div>
                  <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                    {o.agency_name} · {o.company_name}
                  </div>
                </div>
                <span style={{
                  fontSize: '0.7rem', fontWeight: 800, padding: '0.2rem 0.55rem',
                  borderRadius: 6,
                  background: o.status === 'COMPLETED' || o.status === 'DELIVERED'
                    ? 'rgba(52,211,153,0.15)' : o.status === 'CANCELLED' || o.status === 'REJECTED'
                    ? 'rgba(244,63,94,0.15)' : 'rgba(251,191,36,0.15)',
                  color: o.status === 'COMPLETED' || o.status === 'DELIVERED'
                    ? '#34d399' : o.status === 'CANCELLED' || o.status === 'REJECTED'
                    ? '#fb7185' : '#fbbf24'
                }}>
                  {o.status}
                </span>
              </div>
            ))}
          </div>
        )}

        {showDropdown && query.length >= 2 && suggestions.length === 0 && (
          <div style={{
            position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 999,
            background: '#1e293b', border: '1px solid #334155', borderRadius: 12,
            marginTop: 6, padding: '1.25rem', textAlign: 'center', color: '#64748b', fontSize: '0.85rem'
          }}>
            No orders match "{query}"
          </div>
        )}
      </div>

      {/* Empty state — no order selected */}
      {!selectedOrder && (
        <div style={{
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
          gap: '1rem', padding: '4rem 2rem', textAlign: 'center'
        }}>
          <div style={{
            width: 90, height: 90, borderRadius: '50%',
            background: 'linear-gradient(135deg, rgba(56,189,248,0.15), rgba(99,102,241,0.1))',
            border: '2px solid rgba(56,189,248,0.2)',
            display: 'flex', alignItems: 'center', justifyContent: 'center'
          }}>
            <ScanSearch size={40} color="#38bdf8" />
          </div>
          <div>
            <div style={{ fontSize: '1.1rem', fontWeight: 800, color: '#f8fafc' }}>Search for an Order</div>
            <div style={{ fontSize: '0.85rem', color: '#64748b', marginTop: 6 }}>
              Type at least 2 characters of the order number or party name above
            </div>
          </div>
          {/* Quick access - show recent orders as chips */}
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', justifyContent: 'center', marginTop: '0.5rem' }}>
            {accessibleOrders.slice(0, 6).map(o => (
              <button key={o.id} onClick={() => handleSelect(o)}
                style={{
                  padding: '0.4rem 0.85rem', background: '#141f36', border: '1px solid #1e293b',
                  borderRadius: 20, color: '#94a3b8', fontSize: '0.775rem', cursor: 'pointer', fontWeight: 700,
                  transition: 'all 0.15s'
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = '#38bdf8'; e.currentTarget.style.color = '#38bdf8'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = '#1e293b'; e.currentTarget.style.color = '#94a3b8'; }}
              >
                {o.order_number}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ORDER TRACKER CARD */}
      {selectedOrder && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>

          {/* Order Summary Header Card */}
          <div style={{
            background: 'linear-gradient(135deg, #141f36, #0f172a)',
            border: `2px solid ${isCancelled ? 'rgba(244,63,94,0.4)' : isHeld ? 'rgba(251,191,36,0.4)' : 'rgba(56,189,248,0.3)'}`,
            borderRadius: 18, padding: '1.5rem', position: 'relative', overflow: 'hidden'
          }}>
            {/* Glow accent */}
            <div style={{
              position: 'absolute', top: -40, right: -40, width: 180, height: 180,
              borderRadius: '50%',
              background: isCancelled ? 'rgba(244,63,94,0.08)' : isHeld ? 'rgba(251,191,36,0.08)' : 'rgba(56,189,248,0.08)',
              pointerEvents: 'none'
            }} />

            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
              <div>
                <div style={{ fontSize: '0.7rem', fontWeight: 800, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>
                  Order Number
                </div>
                <div style={{ fontSize: '1.65rem', fontWeight: 900, color: '#38bdf8', fontFamily: 'monospace', letterSpacing: '-0.02em' }}>
                  {selectedOrder.order_number}
                </div>
                <div style={{ fontSize: '0.8rem', color: '#94a3b8', marginTop: 4, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Calendar size={13} /> {selectedOrder.order_date}
                </div>
              </div>

              {/* Current Status Badge */}
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontSize: '0.675rem', fontWeight: 800, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6 }}>
                  Current Status
                </div>
                <span style={{
                  display: 'inline-block',
                  padding: '0.45rem 1.1rem',
                  borderRadius: 30,
                  fontSize: '0.825rem', fontWeight: 800,
                  background: isCancelled ? 'rgba(244,63,94,0.2)' : isHeld ? 'rgba(251,191,36,0.2)' : 'rgba(52,211,153,0.15)',
                  color: isCancelled ? '#fb7185' : isHeld ? '#fbbf24' : '#34d399',
                  border: `1px solid ${isCancelled ? 'rgba(244,63,94,0.4)' : isHeld ? 'rgba(251,191,36,0.4)' : 'rgba(52,211,153,0.3)'}`,
                  boxShadow: isCancelled ? '0 0 12px rgba(244,63,94,0.2)' : isHeld ? '0 0 12px rgba(251,191,36,0.2)' : '0 0 12px rgba(52,211,153,0.15)'
                }}>
                  {getStatusLabel(selectedOrder.status)}
                </span>
              </div>
            </div>

            {/* Info Grid */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '1.1rem', marginTop: '1.25rem' }}>
              {[
                { icon: Building2, label: 'Company', value: selectedOrder.company_name, color: '#38bdf8' },
                { icon: MapPin, label: 'Party / Agency', value: selectedOrder.agency_name, color: '#a78bfa' },
                { icon: User, label: 'Salesperson', value: selectedOrder.salesperson_name, color: '#fbbf24' },
                { icon: Boxes, label: 'Quantity', value: `${selectedOrder.total_qty_pcs} PCS  (${selectedOrder.total_box_qty} Boxes)`, color: '#34d399' },
                { icon: BadgeIndianRupee, label: 'Order Value', value: `₹${selectedOrder.total_amount.toLocaleString('en-IN')}`, color: '#f97316' },
                { icon: Truck, label: 'Delivery Type', value: selectedOrder.delivery_type || 'F.O.R', color: '#94a3b8' },
              ].map(info => {
                const Icon = info.icon;
                return (
                  <div key={info.label} style={{ display: 'flex', flexDirection: 'column', gap: '0.2rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', fontSize: '0.675rem', fontWeight: 800, color: '#475569', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                      <Icon size={11} color={info.color} /> {info.label}
                    </div>
                    <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#f8fafc' }}>{info.value || '—'}</div>
                  </div>
                );
              })}
            </div>

            {/* Hold Reason / Remarks */}
            {isHeld && selectedOrder.hold_reason && (
              <div style={{ marginTop: '1rem', padding: '0.75rem', background: 'rgba(251,191,36,0.1)', border: '1px solid rgba(251,191,36,0.3)', borderRadius: 10, fontSize: '0.8rem', color: '#fbbf24' }}>
                ⏸️ <strong>Hold Reason:</strong> {selectedOrder.hold_reason}
                {selectedOrder.hold_remarks && <span style={{ color: '#94a3b8' }}> — {selectedOrder.hold_remarks}</span>}
              </div>
            )}
            {isCancelled && (
              <div style={{ marginTop: '1rem', padding: '0.75rem', background: 'rgba(244,63,94,0.1)', border: '1px solid rgba(244,63,94,0.3)', borderRadius: 10, fontSize: '0.8rem', color: '#fb7185' }}>
                ❌ This order has been <strong>Cancelled</strong>.
              </div>
            )}
          </div>

          {/* VISUAL JOURNEY TIMELINE */}
          <div style={{
            background: '#0f172a', border: '1px solid #1e293b',
            borderRadius: 18, padding: '1.75rem 1.5rem'
          }}>
            <div style={{ fontSize: '0.775rem', fontWeight: 800, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: '1.75rem' }}>
              📍 Order Journey — Live Tracker
            </div>

            {isCancelled ? (
              <div style={{
                display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.75rem',
                padding: '2.5rem', textAlign: 'center'
              }}>
                <XCircle size={48} color="#f43f5e" />
                <div style={{ fontSize: '1.1rem', fontWeight: 800, color: '#fb7185' }}>Order Cancelled</div>
                <div style={{ fontSize: '0.825rem', color: '#64748b' }}>This order was cancelled and will not proceed further.</div>
              </div>
            ) : (
              <div style={{ position: 'relative' }}>
                {/* Vertical connector line */}
                <div style={{
                  position: 'absolute', left: 28, top: 28, bottom: 28, width: 2,
                  background: 'linear-gradient(to bottom, #334155 0%, #1e293b 100%)',
                  zIndex: 0
                }} />

                <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
                  {STAGES.map((stage, idx) => {
                    const Icon = stage.icon;
                    const isDone = idx < activeIdx;
                    const isActive = idx === activeIdx;
                    const isPending = idx > activeIdx;
                    const isLastDone = idx === STAGES.length - 1 && isDone;

                    // Special case for HELD within admin review
                    const isHeldAtThisStage = isHeld && stage.id === 'admin_review';

                    const nodeColor = isDone || isActive
                      ? (isHeldAtThisStage ? '#fbbf24' : stage.color)
                      : '#1e293b';
                    const nodeBorder = isDone || isActive
                      ? (isHeldAtThisStage ? '#fbbf24' : stage.color)
                      : '#334155';
                    const nodeBg = isDone
                      ? (isHeldAtThisStage ? 'rgba(251,191,36,0.2)' : `rgba(${hexToRgb(stage.color)},0.2)`)
                      : isActive
                      ? (isHeldAtThisStage ? 'rgba(251,191,36,0.15)' : `rgba(${hexToRgb(stage.color)},0.15)`)
                      : '#0f172a';

                    // Stage-specific metadata
                    let stageMeta: string | null = null;
                    if (stage.id === 'admin_review' && selectedOrder.approved_by_name) {
                      stageMeta = `Approved by: ${selectedOrder.approved_by_name}${selectedOrder.approved_at ? ' on ' + selectedOrder.approved_at : ''}`;
                    }
                    if (stage.id === 'billing' && selectedOrder.invoice_number) {
                      stageMeta = `Invoice: ${selectedOrder.invoice_number}${selectedOrder.invoice_date ? ' · ' + selectedOrder.invoice_date : ''}${selectedOrder.invoice_amount ? ' · ₹' + selectedOrder.invoice_amount.toLocaleString('en-IN') : ''}`;
                    }
                    if (stage.id === 'dispatched' && selectedOrder.remarks && (selectedOrder.status === 'DISPATCHED' || selectedOrder.status === 'OUT_FOR_DELIVERY')) {
                      stageMeta = selectedOrder.remarks;
                    }

                    return (
                      <div key={stage.id} style={{
                        display: 'flex', gap: '1.25rem', alignItems: 'flex-start',
                        paddingBottom: idx < STAGES.length - 1 ? '1.75rem' : 0,
                        position: 'relative', zIndex: 1
                      }}>
                        {/* Node Circle */}
                        <div style={{ flexShrink: 0, position: 'relative' }}>
                          <div style={{
                            width: 56, height: 56, borderRadius: '50%',
                            background: nodeBg,
                            border: `2px solid ${nodeBorder}`,
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            boxShadow: isActive
                              ? `0 0 0 4px ${isHeldAtThisStage ? 'rgba(251,191,36,0.15)' : stage.glow}, 0 0 20px ${isHeldAtThisStage ? 'rgba(251,191,36,0.25)' : stage.glow}`
                              : isDone
                              ? `0 0 8px ${stage.glow}`
                              : 'none',
                            transition: 'all 0.3s ease'
                          }}>
                            {isHeldAtThisStage ? (
                              <Pause size={22} color="#fbbf24" />
                            ) : isDone ? (
                              <CheckCircle2 size={22} color={stage.color} />
                            ) : isActive ? (
                              <Icon size={22} color={stage.color} />
                            ) : (
                              <Icon size={22} color="#334155" />
                            )}
                          </div>

                          {/* Active pulse ring */}
                          {isActive && !isHeldAtThisStage && (
                            <div style={{
                              position: 'absolute', inset: -6,
                              borderRadius: '50%',
                              border: `2px solid ${stage.color}`,
                              opacity: 0.4,
                              animation: 'pulse 2s ease-in-out infinite'
                            }} />
                          )}
                        </div>

                        {/* Stage Content */}
                        <div style={{ flex: 1, paddingTop: 10 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', flexWrap: 'wrap' }}>
                            <span style={{
                              fontSize: '0.975rem', fontWeight: 800,
                              color: isActive ? stage.color : isDone ? '#f8fafc' : '#475569'
                            }}>
                              {stage.label}
                            </span>

                            {isActive && (
                              <span style={{
                                display: 'inline-flex', alignItems: 'center', gap: '0.3rem',
                                padding: '0.2rem 0.65rem', borderRadius: 20, fontSize: '0.675rem', fontWeight: 900,
                                background: isHeldAtThisStage ? 'rgba(251,191,36,0.2)' : `rgba(${hexToRgb(stage.color)},0.2)`,
                                color: isHeldAtThisStage ? '#fbbf24' : stage.color,
                                border: `1px solid ${isHeldAtThisStage ? 'rgba(251,191,36,0.4)' : stage.color}`,
                                textTransform: 'uppercase', letterSpacing: '0.07em'
                              }}>
                                {isHeldAtThisStage ? <><Pause size={10} /> ON HOLD</> : <><Clock size={10} /> CURRENT STAGE</>}
                              </span>
                            )}

                            {isDone && (
                              <span style={{
                                fontSize: '0.675rem', color: '#34d399', fontWeight: 700,
                                display: 'inline-flex', alignItems: 'center', gap: '0.2rem'
                              }}>
                                <CheckCircle2 size={11} /> Done
                              </span>
                            )}

                            {isPending && (
                              <span style={{ fontSize: '0.675rem', color: '#334155', fontWeight: 700 }}>
                                Pending
                              </span>
                            )}
                          </div>

                          <div style={{
                            fontSize: '0.8rem', color: isPending ? '#334155' : '#94a3b8', marginTop: 3, fontWeight: 500
                          }}>
                            {stage.sublabel}
                          </div>

                          {stageMeta && (isDone || isActive) && (
                            <div style={{
                              marginTop: 8, padding: '0.55rem 0.85rem',
                              background: '#141f36', border: '1px solid #1e293b',
                              borderRadius: 8, fontSize: '0.775rem', color: '#94a3b8',
                              display: 'flex', alignItems: 'center', gap: '0.4rem',
                              maxWidth: 520
                            }}>
                              <ArrowRight size={12} color={stage.color} />
                              <span style={{ color: '#cbd5e1' }}>{stageMeta}</span>
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>

          {/* Return Request Section */}
          {selectedOrder.return_request && (
            <div style={{
              background: '#0f172a',
              border: `1px solid ${selectedOrder.return_request.return_type === 'DAMAGED_RETURN' ? 'rgba(249,115,22,0.35)' : 'rgba(167,139,250,0.35)'}`,
              borderRadius: 18, padding: '1.5rem'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '1rem' }}>
                {selectedOrder.return_request.return_type === 'DAMAGED_RETURN'
                  ? <PackageX size={20} color="#f97316" />
                  : <RefreshCw size={20} color="#a78bfa" />}
                <div style={{ fontWeight: 800, fontSize: '0.95rem', color: '#f8fafc' }}>
                  {selectedOrder.return_request.return_type === 'DAMAGED_RETURN'
                    ? 'Damaged Goods Return Request'
                    : 'Stock Replacement Request'}
                </div>
                <span style={{
                  marginLeft: 'auto', padding: '0.2rem 0.65rem', borderRadius: 20, fontSize: '0.7rem', fontWeight: 800,
                  background: selectedOrder.return_request.status === 'DISPATCH_PROCESSED'
                    ? 'rgba(52,211,153,0.15)' : selectedOrder.return_request.status === 'APPROVED'
                    ? 'rgba(56,189,248,0.15)' : selectedOrder.return_request.status === 'REJECTED'
                    ? 'rgba(244,63,94,0.15)' : 'rgba(251,191,36,0.15)',
                  color: selectedOrder.return_request.status === 'DISPATCH_PROCESSED'
                    ? '#34d399' : selectedOrder.return_request.status === 'APPROVED'
                    ? '#38bdf8' : selectedOrder.return_request.status === 'REJECTED'
                    ? '#fb7185' : '#fbbf24'
                }}>
                  {selectedOrder.return_request.status.replace(/_/g, ' ')}
                </span>
              </div>
              <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>
                Raised by <strong style={{ color: '#fbbf24' }}>{selectedOrder.return_request.requested_by_name}</strong>
                {' · '}Reason: <em>"{selectedOrder.return_request.reason}"</em>
              </div>
            </div>
          )}

          {/* Order Items */}
          {selectedOrder.items && selectedOrder.items.length > 0 && (
            <div style={{ background: '#0f172a', border: '1px solid #1e293b', borderRadius: 18, padding: '1.5rem' }}>
              <div style={{ fontSize: '0.775rem', fontWeight: 800, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: '1rem' }}>
                Order Items
              </div>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid #1e293b' }}>
                    <th style={{ padding: '0.5rem 0.75rem', color: '#64748b', fontWeight: 800, textAlign: 'left', fontSize: '0.7rem', textTransform: 'uppercase' }}>Product</th>
                    <th style={{ padding: '0.5rem 0.75rem', color: '#64748b', fontWeight: 800, textAlign: 'center', fontSize: '0.7rem', textTransform: 'uppercase' }}>Ordered PCS</th>
                    <th style={{ padding: '0.5rem 0.75rem', color: '#64748b', fontWeight: 800, textAlign: 'center', fontSize: '0.7rem', textTransform: 'uppercase' }}>Dispatched PCS</th>
                    <th style={{ padding: '0.5rem 0.75rem', color: '#64748b', fontWeight: 800, textAlign: 'center', fontSize: '0.7rem', textTransform: 'uppercase' }}>Pending PCS</th>
                    <th style={{ padding: '0.5rem 0.75rem', color: '#64748b', fontWeight: 800, textAlign: 'right', fontSize: '0.7rem', textTransform: 'uppercase' }}>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {selectedOrder.items.map(item => (
                    <tr key={item.id} style={{ borderBottom: '1px solid #0d1527' }}>
                      <td style={{ padding: '0.6rem 0.75rem', color: '#f8fafc', fontWeight: 600 }}>
                        {item.product_name}
                        {item.remark && <div style={{ fontSize: '0.675rem', color: '#64748b', marginTop: 2 }}>{item.remark}</div>}
                      </td>
                      <td style={{ padding: '0.6rem 0.75rem', color: '#fbbf24', fontWeight: 800, textAlign: 'center' }}>{item.total_qty_pcs}</td>
                      <td style={{ padding: '0.6rem 0.75rem', color: '#34d399', fontWeight: 800, textAlign: 'center' }}>
                        {item.dispatched_qty_pcs > 0 ? item.dispatched_qty_pcs : <span style={{ color: '#334155' }}>—</span>}
                      </td>
                      <td style={{ padding: '0.6rem 0.75rem', textAlign: 'center', fontWeight: 800 }}>
                        {item.pending_qty_pcs > 0
                          ? <span style={{ color: '#fb7185' }}>{item.pending_qty_pcs}</span>
                          : <span style={{ color: '#34d399' }}>✓ Nil</span>}
                      </td>
                      <td style={{ padding: '0.6rem 0.75rem', color: '#f8fafc', fontWeight: 700, textAlign: 'right' }}>₹{item.total_price.toLocaleString('en-IN')}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr style={{ borderTop: '2px solid #1e293b' }}>
                    <td colSpan={4} style={{ padding: '0.65rem 0.75rem', fontWeight: 800, fontSize: '0.85rem', color: '#94a3b8' }}>Order Total</td>
                    <td style={{ padding: '0.65rem 0.75rem', fontWeight: 900, fontSize: '0.95rem', color: '#34d399', textAlign: 'right' }}>
                      ₹{selectedOrder.total_amount.toLocaleString('en-IN')}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          )}
        </div>
      )}

      <style>{`
        @keyframes pulse {
          0%, 100% { opacity: 0.4; transform: scale(1); }
          50% { opacity: 0.8; transform: scale(1.08); }
        }
      `}</style>
    </div>
  );
};

// Helper: hex to rgb string "r,g,b"
function hexToRgb(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return isNaN(r) ? '148,163,184' : `${r},${g},${b}`;
}
